kind: ConfigMap
apiVersion: v1
metadata:
  name: observability-metrics-custom-allowlist
  namespace: testing
data:
  uwl_metrics_list.yaml: |
    matches:
      - __name__=~"(vllm:.*)"
      - __name__=~"(llm_:.*)"
