apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: testing
commonLabels:
  app: llm-load-test-exporter

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - servicemonitor.yaml
  - configmap.yaml
