---
- name: Install RHOAI Operator
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('kubernetes.core.kustomize', dir = kustomize_dir ~ '/feature/install-rhoai') }}"
    validate_certs: false

- name: Wait for RHOAI operator to be ready
  kubernetes.core.k8s_info:
    namespace: redhat-ods-operator
    kind: Pod
    label_selectors:
      - name=rhods-operator
    wait: true
    wait_timeout: 600
    wait_condition:
      type: Ready
      status: 'True'

- name: Apply RHOAI Config
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('kubernetes.core.kustomize', dir = kustomize_dir ~ '/feature/rhoai/') }}"
    validate_certs: false


